import com.huayu.study.drools.model.Person

global java.util.Set set1 ;
global java.util.Set set2 ;

rule "1"
salience 100
    when
        $person: Person(isDiagnosed == true);
    then
        set1.add($person);
end


rule "2"
salience 99
    when
        $person: Person(isDiagnosed == true);
        $person2: Person(isDiagnosed == false, contact contains $person.uid);
    then
        set2.add($person2);
end


rule "3"
salience 99
    when
        $person: Person(isDiagnosed == true);
        $person2: Person(isDiagnosed == false);
    then
        System.out.println($person.getName() + "_" + $person2.getName() + "_3");
end

rule "4"
salience 99
    when
        $person: Person(isDiagnosed == true, uid == 1);
    then
        System.out.println($person.getName() + "_4");
end


rule "5"
salience 99
    when
        $person: Person(isDiagnosed == true);
        $person2: Person(uid == 1, this == $person);

    then
        System.out.println($person.getName() + "_" + $person2.getName() + "_5");
end

